<?php
  
?>

<form method="post" action="">
<input type="hidden" name="e" value="import_basket" />
<h2>My Pet Warehouse Order Import Utility</h2>
<p>STEP 1: Cut and paste just the order table from the email into excel spreadsheet</p>
<p>STEP 2: Cut and paste all data from spreadsheet into the box below and click the Import button.</p>


<textarea style="width:80%; height:300px;" name="data"></textarea>

<div><input type="submit" name="b" value="Import" ></div>

</form>
