<div style="text-align:center;padding-top:80px;">
<h1> K9 Homes </h1>
</div>

<table >
	<tr>
		<td valign="top" width="200" align="right">
		<b>Contact details:</b>
		</td>
		<td width=20>&nbsp;</td>
		<td valign="top" width="200">
		&nbsp;
		</td>
	</tr>
	<tr>
		<td valign="top" width="200" align="right">
		Address:
		</td>
		<td width=20>&nbsp;</td>
		<td valign="top" width="200">
		107 McEwan Road<br/>
		Heidelberg Heights 3081 VIC Australia
		</td>
	</tr>
	<tr>
		<td valign="top" width="200" align="right">
		Telephone: 
		</td>
		<td width=20>&nbsp;</td>
		<td valign="top" width="200">
		61 3 9455 2277
		</td>
	</tr>
	<tr>
		<td valign="top" width="200" align="right">
		Fax:
		</td>
		<td width=20>&nbsp;</td>
		<td valign="top" width="200">
		61 3 9459 1877
		</td>
	</tr>
	<tr>
		<td valign="top" width="200" align="right">
		Email:
		</td>
		<td width=20>&nbsp;</td>
		<td valign="top" width="200">
		<a href="mailto:sales@K9homes.com.au">sales@K9homes.com.au</a>
		</td>
	</tr>
	<tr>
		<td valign="top" width="200" align="right">
		Web:
		</td>
		<td width=20>&nbsp;</td>
		<td valign="top" width="200">
		<a href="?">www.k9homes.com.au</a>
		</td>
	</tr>
</table>
	
<div style="height:320px;"></div>
default.inc
