<?php


?>

<p>This client does not have an email address recorded. Please enter :</p>
<ul><li>A contact email if they have one</li><li>Or if they dont have one then enter <strong>NA</strong> for Not Available</li><li>OR if they have an email but are unwilling to provide it then enter <strong>NW</strong> for Not Willing to provide</li></ul>
<form method = "post" action = "" name = "login">
                <div style="text-align: center"><h3> Add Client Email </h3>
                <p>&nbsp;</p>
                <table  style="margin-left:120px;text-align: left;">
                    <tr>
                        <td align = "right">
                            Client Email Address:
                        </td>

                        <td align = "left">
                            <input type = text size = 12 name ="login_user" style = "width:200px;">
                        </td>

                       
                    </tr>

                   
                    
                    <tr>
                    <td>&nbsp;</td>
                    <td><input tabindex = "50" type = "submit" name = "e" value = "update_client_email"></td>
                    </tr>
                    
                    
                    
                </table></div>
            </form>
<p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>