<?php


?>


<form method = "post" action = "" name = "login">
                <div style="text-align: center"><h3> User Login </h3>
                <p>&nbsp;</p>
                <table  style="margin-left:120px;text-align: left;">
                    <tr>
                        <td align = "right">
                            Login (email address):
                        </td>

                        <td align = "left">
                            <input type = text size = 12 name = username style = "width:200px;">
                        </td>

                       
                    </tr>

                    <tr>
                        <td align = "right">
                            Password:
                        </td>

                        <td align = "left">
                            <input type = password name = password size = 13 style = "width:200px;">
                        </td>
                    </tr>
                    
                    <tr>
                    <td>&nbsp;</td>
                    <td><input tabindex = "50" type = "submit" name = "e" value = "Login"></td>
                    </tr>
                    
                    <tr>
                    <td>&nbsp;</td>
                    <td >
                    <p>&nbsp;</p>
                    <p style="text-align:center">If you have forgotten your password enter your email address below to recover it</p></td>
                    
                    </tr>
                    <tr>
                    <td>&nbsp;</td>
                    <td><input type = "text" size = "12" name ="recovery_email" style = "width:200px;"><br />
                    <input tabindex = "50" type = "submit" name = "e" value = "Recover Password"></td>
                    </td>
                    </tr>
                    
                    
                </table></div>
            </form>
<p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>