<?php
  

/**
*   Display Vars
*   $error_msg - displayed in view
*   $flash_msg - displayed in view
* 
*   $S->is_valid() Checks if a valid k9user or client login exists returns 0 or 1
*   $S->isInternalUser() checks if login is from k9 user returns 0 or 1
* 
*   $S->is_valid_client() returns client ID if Client logged in else 0
*   $S->getClientID() returns the id for the logged in client or the client selected by k9user else 0
* 
* 
*/





?>