<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
    
    
    <?php $titles = array(
        'edit'=> 'Edit Product',
        'specialprices'=>'Edit Special Prices');
        ?>
        
	<title>eCat Admin: <?php echo $titles[$req['a']]?></title>
	<link rel="stylesheet" type="text/css" href="site.css" >
    
	<script src="http://yui.yahooapis.com/3.4.1/build/yui/yui-min.js"></script>
		
		
</head>
	
	
	